# Generated by Django 5.0.1 on 2024-11-09 07:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(default='0000', max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('installerservice', models.CharField(default='Default Service', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstallerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='solar_estimator.installer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('installer', 'Installer'), ('electricity_provider', 'Electricity Provider')], default='customer', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_license', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(default='profile_pictures/default_profile.jpg', upload_to='profile_pictures/')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('panel_size', models.FloatField(default=0.0)),
                ('vendor_profile', models.ForeignKey(limit_choices_to={'user_role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.product')),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='solar_estimator.profile')),
                ('vendor_profile', models.ForeignKey(limit_choices_to={'user_role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='solar_estimator.profile')),
            ],
        ),
        migrations.AddField(
            model_name='installer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installers', to='solar_estimator.profile'),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('solar_panel_size', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.product')),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bids', to='solar_estimator.profile')),
                ('provider_profile', models.ForeignKey(limit_choices_to={'user_role': 'electricity_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bids', to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_details', models.TextField()),
                ('quote_deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
                ('vendor', models.ForeignKey(limit_choices_to={'profile__user_role': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quoterequest')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_buyback_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('new_buyback_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('provider_profile', models.OneToOneField(limit_choices_to={'user_role': 'electricity_provider'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SolarEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_type', models.CharField(max_length=50)),
                ('solar_irradiance', models.FloatField()),
                ('estimated_size_kw', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payback_period', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='solar_estimator.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_purchased', models.DecimalField(blank=True, decimal_places=2, help_text='Energy purchased in kWh, applicable for completed transactions.', max_digits=10, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Total payment amount for the transaction.', max_digits=10, null=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_profile', models.ForeignKey(blank=True, limit_choices_to={'user_role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transactions', to='solar_estimator.profile')),
                ('provider_profile', models.ForeignKey(limit_choices_to={'user_role': 'electricity_provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='solar_estimator.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
