# Generated by Django 5.0.1 on 2024-11-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_panel_size', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
    ]
