# Generated by Django 5.0.1 on 2024-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0003_alter_installerservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerservice',
            name='installer_address',
            field=models.CharField(default='Unknown', help_text='Address of the installer', max_length=255),
        ),
    ]
