# Generated by Django 5.0.1 on 2024-11-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0004_installerservice_installer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('installer_profile', models.ForeignKey(limit_choices_to={'user_role': 'installer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quoterequest')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequestInstaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_size_min', models.IntegerField()),
                ('panel_size_max', models.IntegerField()),
                ('quote_deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('customer_profile', models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
            ],
        ),
    ]
