# Generated by Django 5.0.1 on 2024-11-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0005_quote_quoterequestinstaller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='price_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quoterequestinstaller'),
        ),
    ]
