# Generated by Django 5.0.1 on 2024-11-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0006_alter_quote_price_estimate_alter_quote_quote_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesubmission',
            name='installer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'installer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installer_quotes', to='solar_estimator.profile'),
        ),
        migrations.AlterField(
            model_name='quotesubmission',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='solar_estimator.profile'),
        ),
    ]
