# Generated by Django 5.0.1 on 2024-11-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0007_quotesubmission_installer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='customer_profile',
            field=models.ForeignKey(limit_choices_to={'user_role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_quotes', to='solar_estimator.profile'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'user_role': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_requests', to='solar_estimator.profile'),
        ),
    ]
