# Generated by Django 5.0.1 on 2024-11-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0008_alter_quoterequest_customer_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSubmissionInstaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('installer', models.ForeignKey(limit_choices_to={'user_role': 'installer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
                ('quote_request_installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quoterequestinstaller')),
            ],
        ),
    ]
