# Generated by Django 5.0.1 on 2024-11-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0009_quotesubmissioninstaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('installer', models.ForeignKey(limit_choices_to={'user_role': 'installer'}, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.profile')),
                ('quote_submission_installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quotesubmissioninstaller')),
            ],
        ),
    ]
