# Generated by Django 5.0.1 on 2024-11-13 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0010_installationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationbooking',
            name='customer_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_installations', to='solar_estimator.profile'),
        ),
        migrations.AddField(
            model_name='installationbooking',
            name='solar_panel_size',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
