# Generated by Django 5.0.1 on 2024-11-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0011_installationbooking_customer_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcodeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode_prefix', models.CharField(max_length=5, unique=True)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
