# Generated by Django 5.0.1 on 2024-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0012_postcoderegion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('vendor', 'Vendor'), ('installer', 'Installer')], default='customer', max_length=20),
        ),
    ]
