# Generated by Django 5.0.1 on 2024-11-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0014_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratesetting',
            name='provider_profile',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='provider_profile',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='RateSetting',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
