# Generated by Django 5.0.1 on 2024-11-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0015_remove_ratesetting_provider_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerservice',
            name='quote_submission_installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installer_services', to='solar_estimator.quotesubmissioninstaller'),
        ),
    ]
