# Generated by Django 5.0.1 on 2024-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0016_installerservice_quote_submission_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
