# Generated by Django 5.0.1 on 2024-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0017_installationbooking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='panel_size',
            field=models.FloatField(default=1.0),
        ),
    ]
