# Generated by Django 5.0.1 on 2024-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0018_alter_product_panel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
