# Generated by Django 5.0.1 on 2024-11-26 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0020_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='panel_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5),
        ),
    ]
