# Generated by Django 5.0.1 on 2024-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0021_alter_product_panel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Battery capacity in kWh', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the battery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_type',
            field=models.CharField(blank=True, choices=[('Li-ion', 'Lithium-Ion'), ('Lead-Acid', 'Lead Acid')], help_text='Type of battery', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_battery',
            field=models.BooleanField(default=False),
        ),
    ]
