# Generated by Django 5.0.1 on 2024-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0022_product_battery_capacity_product_battery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_battery',
            field=models.BooleanField(default=True),
        ),
    ]
