# Generated by Django 5.0.1 on 2024-11-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0024_installerreview_delete_installer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(default='0000', max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('installerservice', models.CharField(default='Default Service', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installers', to='solar_estimator.profile')),
            ],
        ),
    ]
