# Generated by Django 5.0.1 on 2024-11-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0025_installer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationbooking',
            name='quote_submission_installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solar_estimator.quotesubmissioninstaller'),
        ),
    ]
