# Generated by Django 5.0.1 on 2024-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0026_alter_installationbooking_quote_submission_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
