# Generated by Django 5.0.1 on 2024-12-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0027_quoterequest_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='submitted',
        ),
    ]
