# Generated by Django 5.0.1 on 2024-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0028_remove_quoterequest_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
