# Generated by Django 5.0.1 on 2024-12-04 09:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0032_rename_panel_size_max_quoterequestinstaller_panel_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationbooking',
            name='price_per_kw',
            field=models.DecimalField(decimal_places=2, default=Decimal('1200.00'), max_digits=10),
        ),
    ]
