# Generated by Django 5.0.1 on 2024-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0033_installationbooking_price_per_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestinstaller',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
