# Generated by Django 5.0.1 on 2024-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0034_quoterequestinstaller_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequestinstaller',
            name='submitted',
        ),
        migrations.AddField(
            model_name='quote',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
