# Generated by Django 5.0.1 on 2024-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_estimator', '0035_remove_quoterequestinstaller_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestinstaller',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
