--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: solar_estimator_bid; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_bid (
    id bigint NOT NULL,
    bid_amount numeric(10,2) NOT NULL,
    expiration_date date NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_profile_id bigint NOT NULL,
    provider_profile_id bigint NOT NULL
);


--
-- Name: solar_estimator_bid_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_bid ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_bid_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_cartitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    customer_profile_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT solar_estimator_cartitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: solar_estimator_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_installation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_installation (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    solar_panel_size character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    scheduled_date date,
    customer_profile_id bigint NOT NULL
);


--
-- Name: solar_estimator_installation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_installation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_installation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_installer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_installer (
    id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    contact_number character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    license_number character varying(100),
    profile_id bigint NOT NULL,
    city character varying(255),
    installerservice character varying(255) NOT NULL,
    postcode character varying(10) NOT NULL
);


--
-- Name: solar_estimator_installer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_installer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_installer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_installerservice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_installerservice (
    id bigint NOT NULL,
    service_name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(10,2) NOT NULL,
    installer_id bigint NOT NULL
);


--
-- Name: solar_estimator_installerservice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_installerservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_installerservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_order (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    order_date date NOT NULL,
    status character varying(20) NOT NULL,
    vendor_profile_id bigint NOT NULL,
    customer_profile_id bigint,
    product_id bigint,
    CONSTRAINT solar_estimator_order_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: solar_estimator_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_product (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    stock_quantity integer NOT NULL,
    vendor_profile_id bigint NOT NULL,
    brand character varying(100),
    description text,
    image character varying(100),
    panel_size double precision NOT NULL,
    CONSTRAINT solar_estimator_product_stock_quantity_check CHECK ((stock_quantity >= 0))
);


--
-- Name: solar_estimator_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_profile (
    id bigint NOT NULL,
    address character varying(255),
    mobile character varying(15),
    user_role character varying(20) NOT NULL,
    company_name character varying(100),
    user_id integer NOT NULL,
    certificate_no character varying(50),
    company_email character varying(254),
    provider_license character varying(50),
    profile_picture character varying(100) NOT NULL,
    latitude double precision,
    longitude double precision,
    city character varying(255)
);


--
-- Name: solar_estimator_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_quoterequest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_quoterequest (
    id bigint NOT NULL,
    estimation_details text NOT NULL,
    quote_deadline date NOT NULL,
    customer_profile_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    vendor_id integer
);


--
-- Name: solar_estimator_quoterequest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_quoterequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_quoterequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_quotesubmission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_quotesubmission (
    id bigint NOT NULL,
    price_estimate numeric(10,2) NOT NULL,
    notes text,
    submitted_at timestamp with time zone NOT NULL,
    quote_request_id bigint NOT NULL,
    vendor_id bigint NOT NULL,
    status character varying(10) NOT NULL
);


--
-- Name: solar_estimator_quotesubmission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_quotesubmission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_quotesubmission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_ratesetting; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_ratesetting (
    id bigint NOT NULL,
    current_buyback_rate numeric(10,2) NOT NULL,
    new_buyback_rate numeric(5,2),
    effective_date date,
    provider_profile_id bigint NOT NULL
);


--
-- Name: solar_estimator_ratesetting_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_ratesetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_ratesetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_solarestimation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_solarestimation (
    id bigint NOT NULL,
    postcode character varying(10) NOT NULL,
    longitude double precision NOT NULL,
    latitude double precision NOT NULL,
    electricity_bill numeric(10,2) NOT NULL,
    house_type character varying(50) NOT NULL,
    solar_irradiance double precision NOT NULL,
    estimated_size_kw double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    profile_id bigint,
    annual_savings numeric(10,2),
    payback_period numeric(5,2)
);


--
-- Name: solar_estimator_solarestimation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_solarestimation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_solarestimation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solar_estimator_transaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solar_estimator_transaction (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    transaction_type character varying(10) NOT NULL,
    date date NOT NULL,
    description text,
    provider_profile_id bigint NOT NULL,
    customer_profile_id bigint,
    energy_purchased numeric(10,2),
    total_payment numeric(10,2)
);


--
-- Name: solar_estimator_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solar_estimator_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solar_estimator_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session


--
-- Name: solar_estimator_bid solar_estimator_bid_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_bid


--
-- Name: solar_estimator_cartitem solar_estimator_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_cartitem


--
-- Name: solar_estimator_installation solar_estimator_installation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installation


--
-- Name: solar_estimator_installer solar_estimator_installer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installer


--
-- Name: solar_estimator_installerservice solar_estimator_installerservice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installerservice


--
-- Name: solar_estimator_order solar_estimator_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_order


--
-- Name: solar_estimator_product solar_estimator_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_product


--
-- Name: solar_estimator_profile solar_estimator_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_profile


--
-- Name: solar_estimator_profile solar_estimator_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_profile
    ADD CONSTRAINT solar_estimator_profile_user_id_key UNIQUE (user_id);


--
-- Name: solar_estimator_quoterequest solar_estimator_quoterequest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quoterequest


--
-- Name: solar_estimator_quotesubmission solar_estimator_quotesubmission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quotesubmission


--
-- Name: solar_estimator_ratesetting solar_estimator_ratesetting_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_ratesetting


--
-- Name: solar_estimator_ratesetting solar_estimator_ratesetting_provider_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_ratesetting
    ADD CONSTRAINT solar_estimator_ratesetting_provider_profile_id_key UNIQUE (provider_profile_id);


--
-- Name: solar_estimator_solarestimation solar_estimator_solarestimation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_solarestimation


--
-- Name: solar_estimator_transaction solar_estimator_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_transaction


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: solar_estimator_bid_customer_profile_id_7fddca52; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_bid_customer_profile_id_7fddca52 ON public.solar_estimator_bid USING btree (customer_profile_id);


--
-- Name: solar_estimator_bid_provider_profile_id_f51ab1ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_bid_provider_profile_id_f51ab1ff ON public.solar_estimator_bid USING btree (provider_profile_id);


--
-- Name: solar_estimator_cartitem_customer_profile_id_3c0ec9bf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_cartitem_customer_profile_id_3c0ec9bf ON public.solar_estimator_cartitem USING btree (customer_profile_id);


--
-- Name: solar_estimator_cartitem_product_id_4a4017f6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_cartitem_product_id_4a4017f6 ON public.solar_estimator_cartitem USING btree (product_id);


--
-- Name: solar_estimator_installation_customer_profile_id_b9239287; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_installation_customer_profile_id_b9239287 ON public.solar_estimator_installation USING btree (customer_profile_id);


--
-- Name: solar_estimator_installer_profile_id_195b7416; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_installer_profile_id_195b7416 ON public.solar_estimator_installer USING btree (profile_id);


--
-- Name: solar_estimator_installerservice_installer_id_2065add4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_installerservice_installer_id_2065add4 ON public.solar_estimator_installerservice USING btree (installer_id);


--
-- Name: solar_estimator_order_customer_profile_id_3ecc451c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_order_customer_profile_id_3ecc451c ON public.solar_estimator_order USING btree (customer_profile_id);


--
-- Name: solar_estimator_order_product_id_26906c82; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_order_product_id_26906c82 ON public.solar_estimator_order USING btree (product_id);


--
-- Name: solar_estimator_order_vendor_profile_id_c53099cd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_order_vendor_profile_id_c53099cd ON public.solar_estimator_order USING btree (vendor_profile_id);


--
-- Name: solar_estimator_product_vendor_profile_id_743bcd8f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_product_vendor_profile_id_743bcd8f ON public.solar_estimator_product USING btree (vendor_profile_id);


--
-- Name: solar_estimator_quoterequest_customer_profile_id_7f879048; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_quoterequest_customer_profile_id_7f879048 ON public.solar_estimator_quoterequest USING btree (customer_profile_id);


--
-- Name: solar_estimator_quoterequest_vendor_id_98b22ce0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_quoterequest_vendor_id_98b22ce0 ON public.solar_estimator_quoterequest USING btree (vendor_id);


--
-- Name: solar_estimator_quotesubmission_quote_request_id_e1892082; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_quotesubmission_quote_request_id_e1892082 ON public.solar_estimator_quotesubmission USING btree (quote_request_id);


--
-- Name: solar_estimator_quotesubmission_vendor_id_40d16869; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_quotesubmission_vendor_id_40d16869 ON public.solar_estimator_quotesubmission USING btree (vendor_id);


--
-- Name: solar_estimator_solarestimation_profile_id_0b0ed772; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_solarestimation_profile_id_0b0ed772 ON public.solar_estimator_solarestimation USING btree (profile_id);


--
-- Name: solar_estimator_solarestimation_user_id_6920ab7a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_solarestimation_user_id_6920ab7a ON public.solar_estimator_solarestimation USING btree (user_id);


--
-- Name: solar_estimator_transaction_customer_profile_id_5864ae93; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_transaction_customer_profile_id_5864ae93 ON public.solar_estimator_transaction USING btree (customer_profile_id);


--
-- Name: solar_estimator_transaction_provider_profile_id_62c47029; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX solar_estimator_transaction_provider_profile_id_62c47029 ON public.solar_estimator_transaction USING btree (provider_profile_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_bid solar_estimator_bid_customer_profile_id_7fddca52_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_bid
    ADD CONSTRAINT solar_estimator_bid_customer_profile_id_7fddca52_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_bid solar_estimator_bid_provider_profile_id_f51ab1ff_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_bid
    ADD CONSTRAINT solar_estimator_bid_provider_profile_id_f51ab1ff_fk_solar_est FOREIGN KEY (provider_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_cartitem solar_estimator_cart_customer_profile_id_3c0ec9bf_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_cartitem
    ADD CONSTRAINT solar_estimator_cart_customer_profile_id_3c0ec9bf_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_cartitem solar_estimator_cart_product_id_4a4017f6_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_cartitem
    ADD CONSTRAINT solar_estimator_cart_product_id_4a4017f6_fk_solar_est FOREIGN KEY (product_id) REFERENCES public.solar_estimator_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_installation solar_estimator_inst_customer_profile_id_b9239287_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installation
    ADD CONSTRAINT solar_estimator_inst_customer_profile_id_b9239287_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_installerservice solar_estimator_inst_installer_id_2065add4_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installerservice
    ADD CONSTRAINT solar_estimator_inst_installer_id_2065add4_fk_solar_est FOREIGN KEY (installer_id) REFERENCES public.solar_estimator_installer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_installer solar_estimator_inst_profile_id_195b7416_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_installer
    ADD CONSTRAINT solar_estimator_inst_profile_id_195b7416_fk_solar_est FOREIGN KEY (profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_order solar_estimator_orde_customer_profile_id_3ecc451c_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_order
    ADD CONSTRAINT solar_estimator_orde_customer_profile_id_3ecc451c_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_order solar_estimator_orde_product_id_26906c82_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_order
    ADD CONSTRAINT solar_estimator_orde_product_id_26906c82_fk_solar_est FOREIGN KEY (product_id) REFERENCES public.solar_estimator_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_order solar_estimator_orde_vendor_profile_id_c53099cd_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_order
    ADD CONSTRAINT solar_estimator_orde_vendor_profile_id_c53099cd_fk_solar_est FOREIGN KEY (vendor_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_product solar_estimator_prod_vendor_profile_id_743bcd8f_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_product
    ADD CONSTRAINT solar_estimator_prod_vendor_profile_id_743bcd8f_fk_solar_est FOREIGN KEY (vendor_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_profile solar_estimator_profile_user_id_a93211b7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_profile
    ADD CONSTRAINT solar_estimator_profile_user_id_a93211b7_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_quoterequest solar_estimator_quot_customer_profile_id_7f879048_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quoterequest
    ADD CONSTRAINT solar_estimator_quot_customer_profile_id_7f879048_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_quotesubmission solar_estimator_quot_quote_request_id_e1892082_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quotesubmission
    ADD CONSTRAINT solar_estimator_quot_quote_request_id_e1892082_fk_solar_est FOREIGN KEY (quote_request_id) REFERENCES public.solar_estimator_quoterequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_quotesubmission solar_estimator_quot_vendor_id_40d16869_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quotesubmission
    ADD CONSTRAINT solar_estimator_quot_vendor_id_40d16869_fk_solar_est FOREIGN KEY (vendor_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_quoterequest solar_estimator_quoterequest_vendor_id_98b22ce0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_quoterequest
    ADD CONSTRAINT solar_estimator_quoterequest_vendor_id_98b22ce0_fk_auth_user_id FOREIGN KEY (vendor_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_ratesetting solar_estimator_rate_provider_profile_id_c8617ffa_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_ratesetting
    ADD CONSTRAINT solar_estimator_rate_provider_profile_id_c8617ffa_fk_solar_est FOREIGN KEY (provider_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_solarestimation solar_estimator_sola_profile_id_0b0ed772_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_solarestimation
    ADD CONSTRAINT solar_estimator_sola_profile_id_0b0ed772_fk_solar_est FOREIGN KEY (profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_solarestimation solar_estimator_sola_user_id_6920ab7a_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_solarestimation
    ADD CONSTRAINT solar_estimator_sola_user_id_6920ab7a_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_transaction solar_estimator_tran_customer_profile_id_5864ae93_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_transaction
    ADD CONSTRAINT solar_estimator_tran_customer_profile_id_5864ae93_fk_solar_est FOREIGN KEY (customer_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: solar_estimator_transaction solar_estimator_tran_provider_profile_id_62c47029_fk_solar_est; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solar_estimator_transaction
    ADD CONSTRAINT solar_estimator_tran_provider_profile_id_62c47029_fk_solar_est FOREIGN KEY (provider_profile_id) REFERENCES public.solar_estimator_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

