from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
#from .views import CustomLoginView

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('install_requests/', views.install_requests, name='install_requests'),
    path('install-request/<int:id>/', views.install_request_detail, name='install_request_detail'),
    path('orders/', views.orders, name='orders'),
    path('estimator/', views.estimator, name='estimator'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),  
    path('logout/', views.logout_view, name='logout'),
    path('user-management/', views.user_management, name='user_management'),
    path('user-management/edit/<int:user_id>/', views.edit_user, name='edit_user'),
    path('user-management/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    #path('installation_dashboard/', views.installation_dashboard, name='installation_dashboard'),
    path('installation/<int:installation_id>/update_status/<str:status>/', views.update_installation_status, name='update_installation_status'),
    path('installation/<int:installation_id>/', views.installation_detail, name='installation_detail'),
    path('add-installation-service/', views.add_installation_service, name='add_installation_service'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('add_user/', views.add_user, name='add_user'),
    path('reports/', views.reports, name='reports'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),
    path('dashboard/customer/', views.customer_dashboard, name='customer_dashboard'),
    path('dashboard/vendor/', views.vendor_dashboard, name='vendor_dashboard'),
    path('dashboard/installer/', views.installation_dashboard, name='installer_dashboard'),
    path('dashboard/vendor/add_product/', views.add_product, name='add_product'),
    path('dashboard/vendor/edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('dashboard/vendor/delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('dashboard/vendor/update_order_status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('dashboard/vendor/submit_quote/<int:quote_request_id>/', views.submit_quote, name='submit_quote'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/', views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('view_product/<int:product_id>/', views.view_product, name='view_product'),
    path('not-authorized/', views.not_authorized, name='not_authorized'),
    path("estimate/", views.estimate_solar_size, name="estimate_solar_size"),
    path("view_estimations/", views.view_estimations, name="view_estimations"),
    path('estimation_result/', views.estimation_result, name='estimation_result'),
    path('product_vendors/', views.product_vendors, name='product_vendors'),
    path('installation_services/', views.installation_services, name='installation_services'),
    path('shopping_cart/', views.shopping_cart, name='shopping_cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_confirmation/', views.order_confirmation, name='order_confirmation'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('cart/edit/<int:item_id>/', views.edit_cart_item, name='edit_cart_item'),
    path('order/<int:order_id>/', views.view_order_details, name='view_order_details'),
    path('dashboard/vendor/update_order_status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('order/<int:order_id>/', views.order_details, name='order_details'),
    path('request-quote/<int:estimation_id>/', views.request_quote, name='request_quote'),
    path('submit-quote/<int:quote_request_id>/', views.submit_quote, name='submit_quote'),
    path('dashboard/customer/quotes/', views.customer_quotes, name='customer_quotes'),
    path('quotes/accept/<int:quote_id>/', views.accept_quote, name='accept_quote'),
    path('quotes/decline/<int:quote_id>/', views.decline_quote, name='decline_quote'),
    path('installation-service/update/<int:service_id>/', views.update_installation_service, name='update_installation_service'),
    path('installation-service/delete/<int:service_id>/', views.delete_installation_service, name='delete_installation_service'),
    path('installation-service/<int:service_id>/view/', views.view_installation_service, name='view_installation_service'),
    path('get-quote/<int:estimation_id>/', views.get_quote, name='get_quote'),
    path('book-service/<int:service_id>/', views.book_service, name='book_service'),
    path('installer/<int:installer_id>/', views.installer_details, name='installer_details'),
    path('installer/<int:installer_id>/review/', views.submit_installer_review, name='submit_installer_review'),
    #path('submit-quote1/<int:quote_request_id>/', views.submit_quote1, name='submit_quote1'),
    #path('accept_or_decline_quote/<int:quote_id>/', views.accept_or_decline_quote, name='accept_or_decline_quote'),
    path('respond-to-quote/<int:quote_request_id>/', views.respond_to_quote, name='respond_to_quote'),
    path('quote/accept/<int:quote_submission_id>/', views.accept_installation, name='accept_installation'),
    path('quote/decline/<int:quote_submission_id>/', views.decline_installation, name='decline_installation'),
    path('installation/<int:installation_id>/update_status/<str:status>/', views.update_installation_status, name='update_installation_status'),
    path('install-request/<int:booking_id>/', views.install_request_detail, name='install_request_detail'),
    path('installation/<int:installation_id>/update_status/<str:status>/', views.update_installation_status, name='update_install_status'),
    path('search/', views.search_results, name='search_results'),
    path('solar-schemes/', views.solar_schemes, name='solar_schemes'),
    path('order/<int:order_id>/receipt/', views.generate_pdf_receipt, name='generate_pdf_receipt'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('vendor/quotes/', views.vendor_view_quotes, name='vendor_view_quotes'),
    path('installations/completed/', views.completed_installations, name='completed_installations'),
    path('installation/<int:installation_id>/detail/', views.installation_detail, name='installation_detail'),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)